### ISSUE TITLE
Fix complexity issue

### ISSUE THREAD

**Issue by depado** [Depado/go-b0tsec#9]
As for now there are at least 3 functions that are too complex, according to gocyclo ([see this for more details](http://goreportcard.com/report/Depado/go-b0tsec))

For the Init function of the plugins/init.go, this should be fixed with [init functions](https://golang.org/doc/effective_go.html#initialization)

Also there are a lot of files where golint complains.

**Comment by nado** [comment]
- [X] golint perfect now
- [X] gofmt -s for one file (/github.com/Depado/go-b0tsec/utils/string_test.go)
- [X] gocyclo : only plugins/init.go remains

All are fixed in https://github.com/Depado/go-b0tsec/pull/14

**Comment by depado** [comment]
Amazing :smile:
